// This file was generated by Slater.app - index.js

let lenis = null;
history.scrollRestoration = "manual";

const hasLenis = typeof window.Lenis !== "undefined";
const hasScrollTrigger = typeof window.ScrollTrigger !== "undefined";
var mobileQuery = window.matchMedia('(max-width: 450px)');

var tabletPortraitQuery = window.matchMedia('(min-width: 768px) and (max-width: 991px)');
var tabletLandscapeQuery = window.matchMedia('(min-width: 992px) and (max-width: 1280px)');

CustomEase.create("smooth", "M0,0 C0.5,0 0,1 1,1")
CustomEase.create("osmo", "M0,0 C0.625,0.05 0,1 1,1")
CustomEase.create("relaxed", "M0,0 C0.7,0 0.3,1 1,1")

function initLenis() {
  if (lenis) return; // already created

  lenis = new Lenis({
    // lerp: 0.15,
    wheelMultiplier: 1.25,
    prevent: (el) => el.classList.contains('tp-fldv_c')
  });

  lenis.on("scroll", ScrollTrigger.update);

  gsap.ticker.add((time) => {
    lenis.raf(time * 1000);
  });

  gsap.ticker.lagSmoothing(0);
}

function resetPage(container) {
  window.scrollTo(0, 0);
  if (container) gsap.set(container, { clearProps: "position,top,left,right" });

  if (hasLenis) {
    lenis.resize();
    lenis.start();
  }
}

function parents(element, selector) {
  const parentsArray = [];
  let currentElement = element.parentElement;

  while (currentElement !== null) {
    if (currentElement.matches(selector)) {
      parentsArray.push(currentElement);
    }
    currentElement = currentElement.parentElement;
  }

  return parentsArray;
}

CustomEase.create("osmo-ease", "0.625, 0.05, 0, 1")

function initSliders() {
  const sliderWrappers = gsap.utils.toArray(document.querySelectorAll(
    '[data-centered-slider="wrapper"]'));

  sliderWrappers.forEach((sliderWrapper) => {
    const slides = gsap.utils.toArray(sliderWrapper.querySelectorAll(
      '[data-centered-slider="slide"]'));
    const bullets = gsap.utils.toArray(sliderWrapper.querySelectorAll(
      '[data-centered-slider="bullet"]'));
    const prevButton = sliderWrapper.querySelector('[data-centered-slider="prev-button"]');
    const nextButton = sliderWrapper.querySelector('[data-centered-slider="next-button"]');

    let activeElement;
    let activeBullet;
    let currentIndex = 0;
    let autoplay;

    // Autoplay is now enabled/disabled via a boolean attribute.
    const autoplayEnabled = sliderWrapper.getAttribute('data-slider-autoplay') === 'true';

    // If enabled, get the autoplay duration (in seconds) from the separate attribute.
    const autoplayDuration = autoplayEnabled ? parseFloat(sliderWrapper.getAttribute(
      'data-slider-autoplay-duration')) || 0 : 0;

    // Dynamically assign unique IDs to slides
    slides.forEach((slide, i) => {
      slide.setAttribute("id", `slide-${i}`);
    });

    // Set ARIA attributes on bullets if they exist
    if (bullets && bullets.length > 0) {
      bullets.forEach((bullet, i) => {
        bullet.setAttribute("aria-controls", `slide-${i}`);
        bullet.setAttribute("aria-selected", i === currentIndex ? "true" : "false");
      });
    }

    const loop = horizontalLoop(slides, {
      paused: true,
      draggable: true,
      center: true,
      onChange: (element, index) => {
        currentIndex = index;

        if (activeElement) activeElement.classList.remove("active");
        element.classList.add("active");
        activeElement = element;

        if (bullets && bullets.length > 0) {
          if (activeBullet) activeBullet.classList.remove("active");
          if (bullets[index]) {
            bullets[index].classList.add("active");
            activeBullet = bullets[index];
          }
          bullets.forEach((bullet, i) => {
            bullet.setAttribute("aria-selected", i === index ? "true" : "false");
          });
        }

      }
    });

    // On initialization, center the slider
    loop.toIndex(2, { duration: 0.01 });

    function startAutoplay() {
      if (autoplayDuration > 0 && !autoplay) {
        const repeat = () => {
          loop.next({ ease: "osmo-ease", duration: 0.725 });
          autoplay = gsap.delayedCall(autoplayDuration, repeat);
        };
        autoplay = gsap.delayedCall(autoplayDuration, repeat);
      }
    }

    function stopAutoplay() {
      if (autoplay) {
        autoplay.kill();
        autoplay = null;
      }
    }

    // Start/stop autoplay based on viewport visibility via ScrollTrigger
    ScrollTrigger.create({
      trigger: sliderWrapper,
      start: "top bottom",
      end: "bottom top",
      onEnter: startAutoplay,
      onLeave: stopAutoplay,
      onEnterBack: startAutoplay,
      onLeaveBack: stopAutoplay
    });

    // Pause autoplay on mouse hover over the slider
    sliderWrapper.addEventListener("mouseenter", stopAutoplay);
    sliderWrapper.addEventListener("mouseleave", () => {
      if (ScrollTrigger.isInViewport(sliderWrapper)) startAutoplay();
    });

    // Slide click event for direct navigation
    slides.forEach((slide, i) => {
      slide.addEventListener("click", () => {
        loop.toIndex(i, { ease: "osmo-ease", duration: 0.725 });
      });
    });

    // Bullets click event for direct navigation (if available)
    if (bullets && bullets.length > 0) {
      bullets.forEach((bullet, i) => {
        bullet.addEventListener("click", () => {
          loop.toIndex(i, { ease: "osmo-ease", duration: 0.725 });
          if (activeBullet) activeBullet.classList.remove("active");
          bullet.classList.add("active");
          activeBullet = bullet;
          bullets.forEach((b, j) => {
            b.setAttribute("aria-selected", j === i ? "true" : "false");
          });
        });
      });
    }

    // Prev/Next button listeners (if the buttons exist)
    if (prevButton) {
      prevButton.addEventListener("click", () => {
        let newIndex = currentIndex - 1;
        if (newIndex < 0) newIndex = slides.length - 1;
        loop.toIndex(newIndex, { ease: "osmo-ease", duration: 0.725 });
      });
    }

    if (nextButton) {
      nextButton.addEventListener("click", () => {
        let newIndex = currentIndex + 1;
        if (newIndex >= slides.length) newIndex = 0;
        loop.toIndex(newIndex, { ease: "osmo-ease", duration: 0.725 });
      });
    }

  });
}

document.addEventListener("DOMContentLoaded", () => {
  initSliders()
})

// GSAP Helper function to create a looping slider
// Read more: https://gsap.com/docs/v3/HelperFunctions/helpers/seamlessLoop
function horizontalLoop(items, config) {
  let timeline;
  items = gsap.utils.toArray(items);
  config = config || {};
  gsap.context(() => {
    let onChange = config.onChange,
      lastIndex = 0,
      tl = gsap.timeline({
        repeat: config.repeat,
        onUpdate: onChange && function () {
          let i = tl.closestIndex();
          if (lastIndex !== i) {
            lastIndex = i;
            onChange(items[i], i);
          }
        },
        paused: config.paused,
        defaults: { ease: "none" },
        onReverseComplete: () => tl.totalTime(tl.rawTime() + tl.duration() * 100)
      }),
      length = items.length,
      startX = items[0].offsetLeft,
      times = [],
      widths = [],
      spaceBefore = [],
      xPercents = [],
      curIndex = 0,
      indexIsDirty = false,
      center = config.center,
      pixelsPerSecond = (config.speed || 1) * 100,
      snap = config.snap === false ? v => v : gsap.utils.snap(config.snap || 1),
      timeOffset = 0,
      container = center === true ? items[0].parentNode : gsap.utils.toArray(center)[0] ||
      items[0].parentNode,
      totalWidth,
      getTotalWidth = () => items[length - 1].offsetLeft + xPercents[length - 1] / 100 * widths[
        length - 1] - startX + spaceBefore[0] + items[length - 1].offsetWidth * gsap
      .getProperty(items[length - 1], "scaleX") + (parseFloat(config.paddingRight) || 0),
      populateWidths = () => {
        let b1 = container.getBoundingClientRect(),
          b2;
        items.forEach((el, i) => {
          widths[i] = parseFloat(gsap.getProperty(el, "width", "px"));
          xPercents[i] = snap(parseFloat(gsap.getProperty(el, "x", "px")) / widths[i] *
            100 + gsap.getProperty(el, "xPercent"));
          b2 = el.getBoundingClientRect();
          spaceBefore[i] = b2.left - (i ? b1.right : b1.left);
          b1 = b2;
        });
        gsap.set(items, {
          xPercent: i => xPercents[i]
        });
        totalWidth = getTotalWidth();
      },
      timeWrap,
      populateOffsets = () => {
        timeOffset = center ? tl.duration() * (container.offsetWidth / 2) / totalWidth : 0;
        center && times.forEach((t, i) => {
          times[i] = timeWrap(tl.labels["label" + i] + tl.duration() * widths[i] / 2 /
            totalWidth - timeOffset);
        });
      },
      getClosest = (values, value, wrap) => {
        let i = values.length,
          closest = 1e10,
          index = 0,
          d;
        while (i--) {
          d = Math.abs(values[i] - value);
          if (d > wrap / 2) {
            d = wrap - d;
          }
          if (d < closest) {
            closest = d;
            index = i;
          }
        }
        return index;
      },
      populateTimeline = () => {
        let i, item, curX, distanceToStart, distanceToLoop;
        tl.clear();
        for (i = 0; i < length; i++) {
          item = items[i];
          curX = xPercents[i] / 100 * widths[i];
          distanceToStart = item.offsetLeft + curX - startX + spaceBefore[0];
          distanceToLoop = distanceToStart + widths[i] * gsap.getProperty(item, "scaleX");
          tl.to(item, {
              xPercent: snap((curX - distanceToLoop) / widths[i] * 100),
              duration: distanceToLoop / pixelsPerSecond
            }, 0)
            .fromTo(item, {
                xPercent: snap((curX - distanceToLoop + totalWidth) / widths[i] *
                  100)
              }, {
                xPercent: xPercents[i],
                duration: (curX - distanceToLoop +
                  totalWidth - curX) / pixelsPerSecond,
                immediateRender: false
              },
              distanceToLoop / pixelsPerSecond)
            .add("label" + i, distanceToStart / pixelsPerSecond);
          times[i] = distanceToStart / pixelsPerSecond;
        }
        timeWrap = gsap.utils.wrap(0, tl.duration());
      },
      refresh = (deep) => {
        let progress = tl.progress();
        tl.progress(0, true);
        populateWidths();
        deep && populateTimeline();
        populateOffsets();
        deep && tl.draggable ? tl.time(times[curIndex], true) : tl.progress(progress, true);
      },
      onResize = () => refresh(true),
      proxy;
    gsap.set(items, { x: 0 });
    populateWidths();
    populateTimeline();
    populateOffsets();
    window.addEventListener("resize", onResize);

    function toIndex(index, vars) {
      vars = vars || {};
      (Math.abs(index - curIndex) > length / 2) && (index += index > curIndex ? -length :
        length); // always go in the shortest direction
      let newIndex = gsap.utils.wrap(0, length, index),
        time = times[newIndex];
      if (time > tl.time() !== index > curIndex && index !==
        curIndex) { // if we're wrapping the timeline's playhead, make the proper adjustments
        time += tl.duration() * (index > curIndex ? 1 : -1);
      }
      if (time < 0 || time > tl.duration()) {
        vars.modifiers = { time: timeWrap };
      }
      curIndex = newIndex;
      vars.overwrite = true;
      gsap.killTweensOf(proxy);
      return vars.duration === 0 ? tl.time(timeWrap(time)) : tl.tweenTo(time, vars);
    }
    tl.toIndex = (index, vars) => toIndex(index, vars);
    tl.closestIndex = setCurrent => {
      let index = getClosest(times, tl.time(), tl.duration());
      if (setCurrent) {
        curIndex = index;
        indexIsDirty = false;
      }
      return index;
    };
    tl.current = () => indexIsDirty ? tl.closestIndex(true) : curIndex;
    tl.next = vars => toIndex(tl.current() + 1, vars);
    tl.previous = vars => toIndex(tl.current() - 1, vars);
    tl.times = times;
    tl.progress(1, true).progress(0, true); // pre-render for performance
    if (config.reversed) {
      tl.vars.onReverseComplete();
      tl.reverse();
    }
    if (config.draggable && typeof (Draggable) === "function") {
      proxy = document.createElement("div")
      let wrap = gsap.utils.wrap(0, 1),
        ratio, startProgress, draggable, dragSnap, lastSnap, initChangeX, wasPlaying,
        align = () => tl.progress(wrap(startProgress + (draggable.startX - draggable.x) *
          ratio)),
        syncIndex = () => tl.closestIndex(true);
      typeof (InertiaPlugin) === "undefined" && console.warn(
        "InertiaPlugin required for momentum-based scrolling and snapping. https://greensock.com/club"
      );
      draggable = Draggable.create(proxy, {
        trigger: items[0].parentNode,
        type: "x",
        onPressInit() {
          let x = this.x;
          gsap.killTweensOf(tl);
          wasPlaying = !tl.paused();
          tl.pause();
          startProgress = tl.progress();
          refresh();
          ratio = 1 / totalWidth;
          initChangeX = (startProgress / -ratio) - x;
          gsap.set(proxy, { x: startProgress / -ratio });
        },
        onDrag: align,
        onThrowUpdate: align,
        overshootTolerance: 0,
        inertia: true,
        snap(value) {
          if (Math.abs(startProgress / -ratio - this.x) < 10) {
            return lastSnap + initChangeX
          }
          let time = -(value * ratio) * tl.duration(),
            wrappedTime = timeWrap(time),
            snapTime = times[getClosest(times, wrappedTime, tl.duration())],
            dif = snapTime - wrappedTime;
          Math.abs(dif) > tl.duration() / 2 && (dif += dif < 0 ? tl.duration() : -tl
            .duration());
          lastSnap = (time + dif) / tl.duration() / -ratio;
          return lastSnap;
        },
        onRelease() {
          syncIndex();
          draggable.isThrowing && (indexIsDirty = true);
        },
        onThrowComplete: () => {
          syncIndex();
          wasPlaying && tl.play();
        }
      })[0];
      tl.draggable = draggable;
    }
    tl.closestIndex(true);
    lastIndex = curIndex;
    onChange && onChange(items[curIndex], curIndex);
    timeline = tl;
    return () => window.removeEventListener("resize", onResize);
  });
  return timeline;

}

function splineLoader() {

  const peSpline = document.querySelector('.pe--spline--loader');

  if (!peSpline) return;

  let container = peSpline.querySelector('.spline--canvas');

  var spline = new SplineLoader(container, peSpline);

}

function siteHeader() {

  const header = document.querySelector('.site-header'),
    menuWrap = header.querySelector('.site-menu'),
    toggle = header.querySelector('.site-nav-toggle');

  var clicks = 0;

  toggle.addEventListener('click', () => {

    clicks++
    if (clicks % 2 == 0) {

      menuWrap.dataset.menu = 'close';
      toggle.classList.remove('active');

    } else {
      menuWrap.dataset.menu = 'open';
      toggle.classList.add('active');
    }

  })

  var headerTl = gsap.timeline({
    scrollTrigger: {
      trigger: document,
      start: 0,
      toggleActions: "play none play reverse",
    }
  })

  headerTl.to(header.querySelectorAll('[data-fixed=hide]'), {
    opacity: 0,
    yPercent: -100,
    duration: .5,
    ease: 'osmo'
  }, 0)

  headerTl.fromTo(header.querySelector('.site-navigation'), {
    width: tabletPortraitQuery.matches ? 300 : mobileQuery.matches ? '100%' : 450
  }, {
    width: tabletPortraitQuery.matches ? 300 : mobileQuery.matches ? '60%' : 350,
    ease: 'osmo',
    duration: .5
  }, 0)

  function siteMenus() {

    const menuItems = document.querySelectorAll('.main-menu-item-link');

    menuItems.forEach(el => {
      el.addEventListener('click', () => {
        if (el.classList.contains('w--current')) return;
        const href = el.getAttribute('href');

        // önce tüm menüden temizle
        menuItems.forEach(e => e.classList.remove('w--current'));
        // sonra eşleşenlere ekle
        document.querySelectorAll(`[href="${CSS.escape(href)}"]`)
          .forEach(e => e.classList.add('w--current'));
      });
    });

  }

  siteMenus();

}

function textUtils() {

  document.querySelectorAll('[data-edit-lines]').forEach(text => {

    const split = SplitText.create(text, {
      type: 'lines , chars',
      mask: 'lines',
      linesClass: 'text_line',
      charsClass: 'text_char',
    })

    if (!mobileQuery.matches) {

      const centerLines = text.dataset.linesCenter.split(" ");
      const rightLines = text.dataset.linesRight.split(" ");

      text.querySelectorAll('.text_line').forEach((line, i) => {
        i++;
        if (centerLines.includes(String(i))) {
          line.classList.add('centered-line');
        }
        if (rightLines.includes(String(i))) {
          line.classList.add('right-line');
        }
      });

    }

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: text,
        start: 'top bottom',
        end: 'bottom center',
        // markers: true,
        scrub: true
      }
    }).to(text.querySelectorAll('.text_char'), {
      opacity: 1,
      stagger: 0.1,
      ease: "linear"
    });

  })

  document.querySelectorAll('[data-text-anim=wordsUp]').forEach(text => {

    const split = SplitText.create(text, {
      type: 'lines , words',
      linesClass: 'text_line',
      wordsClass: 'text_word',
      mask: 'words'
    });

    gsap.to(text.querySelectorAll('.text_word'), {
      yPercent: 0,
      y: 0,
      duration: 1,
      stagger: {
        from: 'start',
        each: 0.05
      },
      ease: "smooth",
      scrollTrigger: {
        trigger: text,
        start: 'top bottom',

      }
    })

  })

  document.querySelectorAll('[data-text-anim=charsUp]').forEach(text => {

    const split = SplitText.create(text, {
      type: 'lines , chars',
      linesClass: 'text_line',
      charsClass: 'text_char',
    });

    gsap.to(text.querySelectorAll('.text_char'), {
      yPercent: 0,
      y: 0,
      duration: 1,
      stagger: {
        from: 'start',
        each: 0.1
      },
      ease: "smooth",
      scrollTrigger: {
        trigger: text,
        start: 'top bottom',

      }
    })

  })

  function textScatterRed(scope) {

    const text = scope;

    var split = SplitText.create(text, {
      type: 'chars',
      charsClass: 'scatter--char'
    });

    gsap.from(scope.querySelectorAll('.scatter--char'), {
      color: '#000000',
      scrambleText: {
        chars: "+/@#$%*()!",
        // speed: 0.2
      },
      duration: .4,
      stagger: 0.05,
      ease: 'smooth',
      scrollTrigger: {
        trigger: scope,
        start: 'top bottom',
        // markers: true,
      }
    })

  }

  document.querySelectorAll('[data-text-anim="scatterRed"]').forEach((scope) => {
    textScatterRed(scope)
  });

  document.fonts.ready.then(() => {
    document.querySelectorAll('[data-text-anim="justifyExpand"]').forEach(text => {

      const start = text.dataset.scrollStart ? text.dataset.scrollStart : 'top bottom';
      const end = text.dataset.scrollEnd ? text.dataset.scrollEnd : 'center center';

      if (mobileQuery.matches) return;

      // hero gibi durumlarda trigger'ı bir üst section yap: data-scroll-trigger=".hero"
      const triggerEl = text.dataset.scrollTrigger ?
        text.closest(text.dataset.scrollTrigger) :
        text;

      let tl;

      SplitText.create(text, {
        type: 'words, lines',
        linesClass: 'justify_line',
        wordsClass: 'justify_word',
        autoSplit: true,
        onSplit: (self) => {
          // önceki timeline + scrollTrigger temizliği
          if (tl) {
            if (tl.scrollTrigger) tl.scrollTrigger.kill();
            tl.kill();
          }

          tl = gsap.timeline({
            scrollTrigger: {
              trigger: triggerEl,
              start: start,
              end: end,
              scrub: true,
              // markers: true
            }
          });

          self.lines.forEach((line, i) => {
            const words = line.querySelectorAll('.justify_word');
            const state = Flip.getState(words);
            line.classList.add('expanded');

            // scrollTrigger YOK — sadece tween/timeline döndürür
            const fl = Flip.from(state, {
              absolute: false,
              ease: 'smooth',
            });

            tl.add(fl, 0.1 * i); // hepsi 0 pozisyonunda, paralel
          });

          // transformlar aynı tick'te uygulandı → görünür yap, flash yok
          gsap.set(text, { autoAlpha: 1 });

          return tl;
        }
      });
    });

    ScrollTrigger.refresh();
  });

  document.querySelectorAll('[data-hover="charsUp"]').forEach(text => {
    const split = SplitText.create(text, {
      type: 'chars',
      mask: 'chars',
      charsClass: 'hover_char',
      onSplit: (split) => {

        // En temiz yol
        split.chars.forEach(el => {
          const clone = el.cloneNode(true);
          clone.classList.add('char-clone');
          el.insertAdjacentElement('afterend', clone);
        });
      }

    });

  })

}

function animUtils() {

  document.querySelectorAll('[data-anim="fadeUp"]').forEach((scope) => {

    const start = scope.dataset.scrollStart ? scope.dataset.scrollStart : 'top bottom';
    const end = scope.dataset.scrollEnd ? scope.dataset.scrollEnd : 'center center';
    const delay = scope.dataset.delay ? parseFloat(scope.dataset.delay) : 0;

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: scope,
        start: start,
        end: end
      }
    });

    tl.from(scope, {
      opacity: 0,
      y: 100,
      duration: 1,
      delay: delay, // timeline içindeyken delay çalışır
      ease: 'smooth',
      onStart: () => scope.classList.add('anim-start')
    });

  });

}

function updateClock() {

  if (!document.querySelector('.live-clock')) return;

  const time = new Date().toLocaleTimeString('en-GB', {
    timeZone: 'Europe/Luxembourg',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false
  });
  document.querySelector('.live-clock').textContent = time;
}

updateClock();
setInterval(updateClock, 1000);

function parallaxUtils() {

  if (mobileQuery.matches) return;

  document.querySelectorAll('[data-parallax]').forEach((scope) => {

    const dir = scope.dataset.parallaxDirection;

    gsap.fromTo(scope, {
      yPercent: 0
    }, {
      yPercent: scope.dataset.parallaxStrength * (dir === 'up' ? -1 : 1),
      ease: 'none',
      scrollTrigger: {
        trigger: scope,
        scrub: true,
        start: 'top bottom',
        end: 'bottom top'
      }
    })

  });

}

function servicesSection() {

  if (!document.querySelector('.our-services-section')) return;
  if (mobileQuery.matches) return;

  const section = document.querySelector('.our-services-section');
  const titlesWrap = section.querySelector('.services-head .service-titles-wrap');
  const indexesWrap = section.querySelector('.services-head .service-indexes-wrap');
  const services = section.querySelectorAll('.service-container');
  const count = services.length;

  // Başlangıç: ilki görünür, diğerleri gizli ve üst üste
  gsap.set(services, { position: 'absolute', inset: 0, opacity: 0 });
  gsap.set(services[0], { opacity: 1 });

  const tl = gsap.timeline({
    defaults: { ease: 'none' },
    scrollTrigger: {
      trigger: section,
      start: 'top top',
      end: () => '+=' + window.innerHeight * count, // her servise 1 ekran
      pin: true,
      scrub: true,
      // markers: true,
    },
  });

  tl.to(count, {}, 'label_a')

  // Her geçiş için 1 birim segment
  services.forEach((el, i) => {

    const text = el.querySelector('.service-text');
    const heading = el.querySelector('.service-heading');
    const list = el.querySelector('.basic-list');
    const work = el.querySelector('.featured-work');

    SplitText.create(text, { type: 'lines', mask: 'lines', linesClass: 'text_line' });
    SplitText.create(heading, { type: 'words', mask: 'words', wordsClass: 'head_word' });

    if (i === count - 1) return; // son servisten sonra geçiş yok

    const next = services[i + 1];

    setTimeout(function () {
      tl.to([titlesWrap, indexesWrap], {
        yPercent: -100 / count * (i + 1),
        ease: "smooth",
      }, 'label_' + i);

      ///// Current Out

      tl.to(el.querySelectorAll('.head_word'), {
        yPercent: -100,
        opacity: 1,
        stagger: 0,
        ease: "smooth",
      }, 'label_' + i);

      tl.to(el.querySelectorAll('.text_line'), {
        yPercent: -100,
        stagger: 0.1,
        ease: "smooth",
      }, 'label_' + i);

      tl.to(el.querySelectorAll('.basic-list-item'), {
        x: 50,
        opacity: 0,
        stagger: 0.1,
        ease: "smooth",
      }, 'label_' + i);

      tl.to(work, {
        yPercent: 100,
        y: 30,
        ease: "smooth",
      }, 'label_' + i);

      ///// Next In

      tl.from(next.querySelectorAll('.head_word'), {
        yPercent: 100,
        opacity: 0,
        stagger: 0,
        onStart: () => {
          gsap.set(next, { opacity: 1 })
        },
        ease: "smooth",
      }, 'label_' + i);

      tl.from(next.querySelectorAll('.text_line'), {
        yPercent: 100,
        stagger: 0.1,
        ease: "smooth",
      }, 'label_' + i);

      tl.from(next.querySelectorAll('.basic-list-item'), {
        x: -50,
        opacity: 0,
        stagger: 0.1,
        ease: "smooth",
      }, 'label_' + i);

      tl.from(next.querySelector('.featured-work'), {
        yPercent: 100,
        y: 30,
        ease: "smooth",
      }, 'label_' + i);

      // tl.to(next, { opacity: 1 }, 'label_' + i);
      tl.to(el, {}, 'label_2_' + i);
    }, 100);

  });

}

function initImagesOnPathScroll() {
  const wrap = document.querySelector('[data-motionpath="wrap"]');

  if (!wrap) return;

  const path = wrap.querySelector('[data-motionpath="path"]');
  const items = wrap.querySelectorAll('[data-motionpath="item"]');
  const itemDetails = wrap.querySelectorAll('[data-motionpath="item-details"]')

  // Set z-index on items, to make sure the 1st item is on top
  gsap.set(items, {
    zIndex: (i, target, all) => all.length - i
  });

  // if there’s an old timeline, grab its progress, reset it, then kill it
  const oldTl = initImagesOnPathScroll.tl;
  let progress = 0;

  if (oldTl) {
    progress = oldTl.progress();
    oldTl.progress(0).kill();
  }

  // create a new timeline + ScrollTrigger
  const tl = gsap.timeline({
    scrollTrigger: {
      trigger: wrap,
      start: 'top top',
      end: 'bottom bottom',
      scrub: true
    },
    defaults: {
      ease: 'none',
      stagger: 0.3 // Define the space between each item
    }
  });

  tl.to(items, {
      duration: 1,
      motionPath: { path, align: path, curviness: 2, alignOrigin: [0.5, 0.5] }
    })
    .fromTo(items, { autoAlpha: 0, }, { autoAlpha: 1, duration: 0.1 },
      0
    )
    .fromTo(items, { filter: mobileQuery.matches ? '' : 'blur(1.5em)' }, {
        filter: mobileQuery
          .matches ? '' : 'blur(0em)',
        duration: 0.5
      },
      0
    )
    .fromTo(itemDetails, { autoAlpha: 0, yPercent: 25 }, {
        autoAlpha: 1,
        yPercent: 0,
        duration: 0.1,
      },
      0.5
    )
    .fromTo(items, { scale: 0.4 }, { scale: 1, duration: 0.65 },
      0
    )
    .to(items, { autoAlpha: 0, filter: mobileQuery.matches ? '' : 'blur(1em)', duration: 0.15 },
      0.85)
    .to(itemDetails, { autoAlpha: 0, duration: 0.05 }, 0.9)

  // jump back to previous spot and refresh
  tl.progress(progress);
  ScrollTrigger.refresh();

  // store it on the function so we can grab it next time
  initImagesOnPathScroll.tl = tl;

  // on first run bind a single debounced resize listener
  if (!initImagesOnPathScroll.resizeHandler) {
    initImagesOnPathScroll.resizeHandler = debounce(() => {
      initImagesOnPathScroll();
    }, 200);
    window.addEventListener('resize', initImagesOnPathScroll.resizeHandler);
  }

  return tl;
}

function debounce(fn, delay = 200) {
  let timeout;
  return () => {
    clearTimeout(timeout);
    timeout = setTimeout(fn, delay);
  };
}

function servicesCard() {

  if (tabletPortraitQuery.matches || mobileQuery.matches) return;

  const cardsWrap = document.querySelector('.services-cards-wrapper');
  if (!cardsWrap) return;

  const cards = document.querySelectorAll('.services-card');

  tl = gsap.timeline({
    scrollTrigger: {
      trigger: '#services-cards',
      start: 'top top+=250',
      end: 'bottom+=3000 bottom',
      scrub: true,
      pin: true,
      pinType: 'transform',
      pinSpacing: 'padding',
      // markers: true
    }
  })

  cards.forEach((item, i) => {
    if (i > 0) {
      item.style.transform = 'translateY(' + i * 72 + 'px)';
      tl.to(item, {
        top: 0
      })
    }
  });

  if (!tabletPortraitQuery.matches && !mobileQuery.matches) {

    ScrollTrigger.create({
      trigger: '#hero-sticky-wrap',
      pin: '#services-hero',
      pinSpacing: false,
      start: 'top top',
      end: 'bottom bottom'
    })
  }

}

function serviceLayers() {

  if (mobileQuery.matches) return;

  let card = document.querySelectorAll('.services-layer'),

    tl = gsap.timeline({
      scrollTrigger: {
        trigger: document.querySelector('#services-layers'),
        start: 'center center',
        end: 'center+=4000 center',
        scrub: true,
        pin: true,
        pinType: 'transform',
        pinSpacing: 'padding',
        // markers: true
      }
    })

  card.forEach((item, i) => {
    if (i > 0) {
      tl.to(item, {
        top: 0
      })
    }
  });

}

function contactMap() {

  const container = document.querySelector('.contact-mapbox-container');

  if (!container) return;

  const mapEl = container.querySelector('.contact-mapbox');

  const cfg = {
    mapboxToken: 'pk.eyJ1IjoieWFsY2lud2ViIiwiYSI6ImNtcW5zdWloZzA3cWwycHIwbnVkYzViMG4ifQ.bXHCD0c3ivyCgEnSeqgrYw',
    mapStyle: 'mapbox://styles/yalcinweb/cmqnswre6000f01qydfa5htot',
    center: [6.1367218, 49.6041655],
    zoom: 17,
    projection: "globe",
    autoRotate: true,
    secondsPerRevolution: 120,
    maxSpinZoom: 5,
    slowSpinZoom: 3,
    flyToDuration: 2000,
    flyToZoom: 5,
    globeOffsetX: -0.2,
    globeOffsetY: 0.25,
    mobile: {
      zoom: 2,
      flyToZoom: 2.5,
      globeOffsetX: 0,
      globeOffsetY: 0.5,
    },
  };

  const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const isSmall = () => window.matchMedia("(max-width: 991px)").matches;
  const val = (key) => (isSmall() && cfg.mobile && cfg.mobile[key] !== undefined) ? cfg.mobile[
    key] : cfg[key];

  if (typeof mapboxgl === "undefined") return;
  if (!cfg.mapboxToken) return;

  mapboxgl.accessToken = cfg.mapboxToken;

  if (!mapEl) return;
  mapEl.id = "locations-map";

  // var lng = wrapper.dataset.lng;
  // var lat = wrapper.dataset.lat;
  // var zoom = wrapper.dataset.zoom;
  // var pitch = wrapper.dataset.pitch;
  // var bearing = wrapper.dataset.bearing;

  // const markers = readMarkers(wrapper);

  const map = new mapboxgl.Map({
    container: mapEl.id,
    style: cfg.mapStyle,
    center: cfg.center, // [lng, lat]
    zoom: cfg.zoom,
    fadeDuration: 1000,
    pitch: 45, // 0-85° — kamera eğimi (3D etki)
    // bearing: bearing, // pusula yönü (derece)
    antialias: true, // 3D katmanlar için kenar yumuşatma
    attributionControl: false,

  });

  const marker = container.querySelector('.map-marker');

  const mark = new mapboxgl.Marker({ element: marker })
    .setLngLat(
      [6.1367218, 49.6041655]
    )
    .addTo(map);

}

function initPortfolioFilter() {
  if (!window.gsap || !window.Flip) return;
  gsap.registerPlugin(Flip);

  var grid = document.querySelector('.portfolio-grid-wrapper');
  var items = gsap.utils.toArray('.single-project');
  var buttons = gsap.utils.toArray('.filter-category');
  if (!grid || !items.length || !buttons.length) return;

  var norm = function (s) { return (s || '').trim().toLowerCase(); };
  var animating = false;

  function catOf(item) {
    var s = item.querySelector('[data-category]') || item;
    return norm(s.getAttribute('data-category'));
  }

  function refreshScroll() {
    if (window.ScrollTrigger) window.ScrollTrigger.refresh();
  }

  function applyFilter(filter) {
    if (animating) return;

    var show = [],
      hide = [];
    items.forEach(function (it) {
      ((filter === 'all' || catOf(it) === filter) ? show : hide).push(it);
    });
    var leaving = hide.filter(function (it) { return !it.classList.contains('is-hidden'); });
    var entering = show.filter(function (it) { return it.classList.contains('is-hidden'); });

    animating = true;

    // Faz 2+3: layout'u Flip ile anime et, girenleri fade-in yap
    function relayout() {
      var state = Flip.getState(items); // çıkanlar artık akışta değil
      hide.forEach(function (it) { it.classList.add('is-hidden'); });
      show.forEach(function (it) { it.classList.remove('is-hidden'); });
      gsap.set(entering, { opacity: 0 }); // popping yerine fade için

      Flip.from(state, {
        duration: 0.5,
        ease: 'power2.inOut',
        scale: true, // transform tabanlı -> boyut sıçraması yok
        onComplete: function () {
          refreshScroll();
          animating = false;
        }
      });
      gsap.to(entering, { opacity: 1, duration: 0.4, delay: 0.15 });
    }

    // Faz 1: çıkanları önce fade-out, bittiğinde relayout
    if (leaving.length) {
      gsap.to(leaving, { opacity: 0, duration: 0.25, onComplete: relayout });
    } else {
      relayout();
    }
  }

  buttons.forEach(function (btn) {
    btn.addEventListener('click', function () {
      buttons.forEach(function (b) { b.classList.remove('category-selected'); });
      btn.classList.add('category-selected');
      // tekrar görünür olan kartların opacity'sini sıfırla (önceki fade-out kalıntısı)
      items.forEach(function (it) {
        if (it.classList.contains('is-hidden')) gsap.set(
          it, { opacity: 1 });
      });
      applyFilter(norm(btn.getAttribute('data-filter')));
    });
  });
}

function DNAScene() {

  if (!window.gsap || !window.ScrollTrigger || mobileQuery.matches) { return; }
  gsap.registerPlugin(ScrollTrigger);

  var section = document.querySelector('#about-dna');
  var wrap = document.querySelector('.dna-infos-wrap');
  var boxes = wrap ? [].slice.call(wrap.querySelectorAll('.dna-info-box')) : [];
  var headline = document.querySelector('#dna-headline');
  if (!section || !boxes.length) return;

  /* ---- Sol-alt dinamik metin: her adım için bir satır (BURAYI DÜZENLE) ---- */
  var PHRASES = [
    'NOUS VOUS OFFRONS <br>UNE CLARTÉ TECHNIQUE, <br>UNE VISION DE MARQUE',
    'NOUS TRANSFORMONS <br>LA COMPLEXITÉ <br>EN STRATÉGIE',
    'NOUS FAÇONNONS <br>LES IDÉES <br>EN EXPÉRIENCE',
    'NOUS RESTONS <br>À VOS CÔTÉS, <br>TOUJOURS'
  ];

  var steps = boxes.length;

  /* kapsayıcı yüksekliği = en uzun kutu (absolute yığında çökmesin) */
  function sizeWrap() {
    var h = 0;
    boxes.forEach(function (b) { h = Math.max(h, b.offsetHeight); });
    if (h) wrap.style.minHeight = h + 'px';
  }
  /* başlık yüksekliğini kilitle (metin değişince zıplama olmasın) */
  function sizeHeadline() {
    if (headline) {
      headline.style.minHeight = '';
      headline.style.minHeight = headline.offsetHeight + 'px';
    }
  }
  sizeWrap();
  sizeHeadline();

  var current = -1,
    first = true;

  function setStep(i) {
    if (i === current) return;
    current = i;
    boxes.forEach(function (b, idx) {
      b.classList.toggle('is-active', idx === i);
      b.classList.toggle('is-past', idx < i);
    });
    if (headline && PHRASES[i] != null) {
      headline.innerHTML = PHRASES[i];
      if (!first) {
        headline.classList.remove('is-anim');
        void headline.offsetWidth; // animasyonu yeniden tetikle
        headline.classList.add('is-anim');
      }
    }
    first = false;
  }

  ScrollTrigger.create({
    trigger: section,
    start: 'top top',
    end: '+=' + (steps * 100) + '%', // adım başına ~1 ekran scroll
    pin: true,
    pinSpacing: true,
    scrub: true,
    // anticipatePin: 1,
    invalidateOnRefresh: true,
    onRefresh: function () {
      sizeWrap();
      sizeHeadline();
    },
    onUpdate: function (self) {
      var i = Math.min(steps - 1, Math.floor(self.progress * steps));
      setStep(i);
    }
  });

  setStep(0);
}

function aboutClientsScene() {
  if (!window.gsap || !window.ScrollTrigger || mobileQuery.matches) { return; }

  function splitLines(el) {
    if (!el) return [];
    var words = (el.textContent || '').trim().split(/\s+/);
    if (!words[0]) return [];
    el.textContent = '';
    // kelimeleri inline-block olarak ekle (offsetTop güvenilir olsun)
    var frag = document.createDocumentFragment();
    var wordSpans = words.map(function (w) {
      var s = document.createElement('span');
      s.textContent = w;
      s.style.display = 'inline-block';
      frag.appendChild(s);
      frag.appendChild(document.createTextNode(' '));
      return s;
    });
    el.appendChild(frag);
    // görsel satırlara göre grupla
    var lines = [],
      cur = null,
      top = null;
    wordSpans.forEach(function (s) {
      var t = s.offsetTop;
      if (top === null || Math.abs(t - top) > 1) {
        cur = [];
        lines.push(cur);
        top = t;
      }
      cur.push(s);
    });
    // block satır sarmalayıcılarıyla yeniden kur (CSS'e bağımlı değil)
    el.textContent = '';
    return lines.map(function (group) {
      var line = document.createElement('span');
      line.className = 'cl-line';
      line.style.display = 'block';
      group.forEach(function (s, i) {
        line.appendChild(s);
        if (i < group.length - 1) line.appendChild(document.createTextNode(' '));
      });
      el.appendChild(line);
      return line;
    });
  }

  var section = document.querySelector('#about-clients');
  var cred = section && section.querySelector('.credentials');
  var boxWrap = section && section.querySelector('.client-box-wrapper');
  if (!section || !cred || !boxWrap) return;

  section.classList.add('cl-init');

  var subtitle = cred.firstElementChild; // "02 // credentials"
  var heading = cred.querySelector('.heading-4');
  var para = cred.querySelector('.credentials-text');
  var boxes = [].slice.call(boxWrap.querySelectorAll('.client-box'));

  if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  var headLines = splitLines(heading);
  var paraLines = splitLines(para);
  var credItems = [];
  if (subtitle) credItems.push(subtitle);
  credItems = credItems.concat(headLines, paraLines);

  // ---- başlangıç: hiçbir şey görünmez, sağda bekler ----
  gsap.set(credItems, { opacity: 0, x: 60 });
  gsap.set(boxes, { opacity: 0, y: 60 });
  gsap.set(cred.querySelectorAll('.credentials-title'), { opacity: 1 }); // wrapper'ı açık tut

  var tl = gsap.timeline({
    scrollTrigger: {
      trigger: section,
      start: 'top top',
      end: '+=320%',
      pin: true,
      pinSpacing: true,
      scrub: true,
      anticipatePin: 1,
      invalidateOnRefresh: true
    }
  });

  // 1) Credentials: sağdan sola fade-in (satırlar staggered)
  tl.to(credItems, { opacity: 1, x: 0, duration: 1, stagger: 0.12, ease: 'power3.out' }, 0);
  // 2) Credentials: sola fade-out (aynı yönde devam)
  tl.to(credItems, { opacity: 0, x: -60, duration: 0.8, stagger: 0.08, ease: 'power3.in' },
    '+=0.5');
  // 3) Client boxes: fade-up in
  tl.to(boxes, { opacity: 1, y: 0, duration: 1, stagger: 0.12, ease: 'power3.out' }, '+=0.15');
  // 4) Client boxes: fade-up out
  tl.to(boxes, { opacity: 0, y: -60, duration: 0.8, stagger: 0.1, ease: 'power3.in' }, '+=0.5');

  ScrollTrigger.refresh();

  return tl;
}

function aboutTeamScene() {
  if (!window.gsap || !window.ScrollTrigger || mobileQuery.matches) { return; }

  var hasMP = !!window.MotionPathPlugin;
  if (hasMP) gsap.registerPlugin(MotionPathPlugin);

  function splitLines(el) {
    if (!el) return [];
    var words = (el.textContent || '').trim().split(/\s+/);
    if (!words[0]) return [];
    el.textContent = '';
    var frag = document.createDocumentFragment();
    var wordSpans = words.map(function (w) {
      var s = document.createElement('span');
      s.textContent = w;
      s.style.display = 'inline-block';
      frag.appendChild(s);
      frag.appendChild(document.createTextNode(' '));
      return s;
    });
    el.appendChild(frag);
    var lines = [],
      cur = null,
      top = null;
    wordSpans.forEach(function (s) {
      var t = s.offsetTop;
      if (top === null || Math.abs(t - top) > 1) {
        cur = [];
        lines.push(cur);
        top = t;
      }
      cur.push(s);
    });
    el.textContent = '';
    return lines.map(function (group) {
      var line = document.createElement('span');
      line.className = 'tm-line';
      line.style.display = 'block';
      group.forEach(function (s, i) {
        line.appendChild(s);
        if (i < group.length - 1) line.appendChild(document.createTextNode(' '));
      });
      el.appendChild(line);
      return line;
    });
  }

  var section = document.querySelector('#about-team');
  if (!section) return;
  section.classList.add('tm-init');

  var subtitle = section.querySelector('.team-section-title');
  var heading = section.querySelector('#team-heading');
  var text = section.querySelector('#team-text');
  var members = [].slice.call(section.querySelectorAll('.team-member'));
  if (!members.length) return;

  if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  // --- title + text: sağdan staggered fade-in, ÇIKIŞ YOK ---
  var headLines = splitLines(heading);
  var paraLines = splitLines(text);
  var credItems = [];
  if (subtitle) credItems.push(subtitle);
  credItems = credItems.concat(headLines, paraLines);

  gsap.set(credItems, { autoAlpha: 0, x: 60 });
  gsap.set([heading, text], { opacity: 1 });

  // --- üyeler: gerçekten ekranın altından gelsin ---
  var fromY = Math.round((window.innerHeight || 800) * 0.6); // ekran altı
  gsap.set(members, {
    autoAlpha: 0,
    x: 60,
    y: fromY,
    scale: 0.88,
    filter: 'blur(24px)',
    transformOrigin: '50% 50%'
  });

  var tl = gsap.timeline({
    scrollTrigger: {
      trigger: section,
      start: 'top top',
      end: '+=520%', // pin mesafesi (tunable)
      pin: true,
      pinSpacing: true,
      scrub: true,
      anticipatePin: 1,
      invalidateOnRefresh: true
    }
  });

  // 1) title + text giriş (kalıcı)
  tl.to(credItems, { autoAlpha: 1, x: 0, duration: 1, stagger: 0.12, ease: 'power3.out' }, 0);
  tl.addLabel('members', '+=0.4');

  var last = members.length - 1;
  members.forEach(function (m, i) {
    var inPos = (i === 0) ? 'members' : '-=0.55';

    if (hasMP) {
      // GİRİŞ — manuel path: alttan -> hafif yana süzül -> merkeze
      tl.to(m, {
        autoAlpha: 1,
        scale: 1,
        filter: 'blur(0px)',
        duration: 1.5,
        ease: 'expo.out',
        motionPath: {
          path: [
            { x: 60, y: fromY }, // ekran altı (başlangıç)
            { x: -34, y: Math.round(fromY * 0.42) }, // yolda hafif sola süzülme
            { x: 0, y: 0 } // merkez (rest)
          ],
          curviness: 1.5,
          autoRotate: false
        }
      }, inPos);
    } else {
      // Fallback (MotionPath yoksa) — yine alttan, y ile
      tl.to(m, {
        autoAlpha: 1,
        x: 0,
        y: 0,
        scale: 1,
        filter: 'blur(0px)',
        duration: 1.5,
        ease: 'expo.out'
      }, inPos);
    }

    if (i < last) {
      // SÜZÜLME — kısa süre merkezde süzülsün
      tl.to(m, { y: -24, scale: 1.03, duration: 0.8, ease: 'sine.inOut' });
      // ÇIKIŞ — yukarı + blur
      tl.to(m, {
        autoAlpha: 0,
        y: -180,
        filter: 'blur(12px)',
        duration: 1.0,
        ease: 'power2.in'
      });
    }
    // son üye: sadece giriş, merkezde net kalır
  });

  ScrollTrigger.refresh();
  return tl;
}

function clientsCarousel() {

  if (!document.querySelectorAll('.clients-carousel').length) return;

  let clientsCarousel = document.querySelectorAll('.clients-carousel');

  clientsCarousel.forEach(($this) => {
    const original = $this.innerHTML
    const originalWidth = $this.offsetWidth

    for (let e = 0; e <= window.innerWidth / originalWidth; e++) {
      $this.innerHTML += original
    }

    $this.style.setProperty('--scroll-width', originalWidth + 'px')

    const speed = 0.025
    const duration = originalWidth * speed
    $this.style.setProperty('--scroll-duration', duration + 's')
  })

}

function initLoaderThreeSteps() {

  if (!document.querySelector('.loading-container')) return;

  var tl = gsap.timeline({
    defaults: {
      ease: "Expo.easeInOut",
      duration: 1,
      onStart: () => {
        setTimeout(function () {
          document.querySelector('.loading-screen').classList.add(
            'loader-active')
        }, 100);

      }
    }
  });

  /* Loading numbers */
  var randomNumbers1 = gsap.utils.random([2, 3, 4]);
  var randomNumbers2 = gsap.utils.random([5, 6]);
  var randomNumbers3 = gsap.utils.random([1, 5]);
  var randomNumbers4 = gsap.utils.random([7, 8, 9]);

  /* Sayfa yüklendi mi? */
  var pageLoaded = document.readyState === "complete";
  window.addEventListener("load", function () {
    pageLoaded = true;
    // Timeline pause noktasında bekliyorsa devam ettir
    if (tl.paused()) {
      tl.play();
    }
  });

  /* Loading Timeline */
  tl.set(".loading-screen", {
    display: "block",
  });

  tl.set(".loading__progress-inner", {
    scaleY: 0,
    transformOrigin: "bottom"
  });

  tl.set(".loading__number-group.is--first .loading__number-wrap, .loading__percentage", {
    yPercent: 100
  });

  tl.set(
    ".loading__number-group.is--second .loading__number-wrap, .loading__number-group.is--third .loading__number-wrap", {
      yPercent: 10
    });

  /* ---- STEP 1 ---- */
  tl.to(".loading__progress-inner", {
    scaleY: (randomNumbers1 + "" + randomNumbers3) / 100,
  });

  tl.to(".loading__percentage", {
    yPercent: 0
  }, "<");

  tl.to(".loading__number-group.is--second .loading__number-wrap", {
    yPercent: (randomNumbers1 - 1) * -10,
  }, "<");

  tl.to(".loading__number-group.is--third .loading__number-wrap", {
    yPercent: (randomNumbers3 - 1) * -10,
  }, "<");

  /* ---- STEP 2 ---- */
  tl.to(".loading__progress-inner", {
    scaleY: (randomNumbers2 + "" + randomNumbers4) / 100,
  });

  tl.to(".loading__number-group.is--second .loading__number-wrap", {
    yPercent: (randomNumbers2 - 1) * -10,
  }, "<");

  tl.to(".loading__number-group.is--third .loading__number-wrap", {
    yPercent: (randomNumbers4 - 1) * -10,
  }, "<");

  /* ---- SAYFA YÜKLENME KONTROLÜ (2. STEP SONRASI) ----
     Sayfa yüklendiyse beklemeden devam eder.
     Yüklenmediyse burada durur, 'load' olayı gelince devam eder. */
  tl.addPause(null, function () {
    if (pageLoaded) {
      tl.play();
    }
    // pageLoaded false ise hiçbir şey yapma → yukarıdaki load listener devam ettirir
  });

  /* ---- STEP 3 (100%) ---- */
  tl.to(".loading__progress-inner", {
    scaleY: 1,
  });

  tl.to(".loading__number-group.is--second .loading__number-wrap", {
    yPercent: -90,
  }, "<");

  tl.to(".loading__number-group.is--third .loading__number-wrap", {
    yPercent: -90,
  }, "<");

  tl.to(".loading__number-group.is--first .loading__number-wrap", {
    yPercent: 0,
  }, "<");

  /* ---- ÇIKIŞ ANIMASYONU ----
     Line yukarı kayar, numaralar yukarı çıkar,
     en son tüm loading ekranı yukarı süzülerek kapanır. */

  // Line yukarı çıkış
  tl.to(".loading__progress-inner", {
    yPercent: -110,
    duration: 1,
  }, "+=0.3");

  // Tüm numaralar yukarı çıkış
  tl.to(".loading__number-group .loading__number-wrap, .loading__percentage", {
    yPercent: -120,
    duration: 1,
  }, "<");

  // Tüm loading ekranı yukarı süzülerek kapanış
  tl.to(".loading-screen", {
    yPercent: -100,
    duration: 1.2,
    onStart: () => {
      initAnimations();
    }
  }, "-=0.6");

  tl.set(".loading-screen", {
    display: "none",
  });
}

let peSpline = null;

const fadeOut = (el, d = 0.4) => gsap.to(el, { opacity: 0, duration: d });
const fadeIn = (el, d = 0.4) => gsap.to(el, { opacity: 1, duration: d });

/* ----- BURADAN AYARLA: süre / easing / spin / stagger -----
   spinY: kaç tam tur (işaretli). reset ileri (+1), form ters (-1).
   spinTarget: spin uygulanacak obje (varsayılan 'Main Cube'). Birden çok için dizi:
               ['Main Cube','Backdrop'] ; tümü için null.
   staggerTotal: TOPLAM stagger süresi (sn). Kaç obje olursa olsun toplam aynı kalır
   (ilk obje 0, son obje staggerTotal gecikmeyle başlar). 0 = stagger yok.            */
const RESET = {
  duration: 1.0,
  ease: 'osmo',
  spinY: 0,
  spinTarget: 'Main Cube',
  staggerTotal: 0.5
};
const FORM = {
  duration: 1.0,
  ease: 'osmo',
  spinY: 0,
  spinTarget: 'Main Cube',
  staggerTotal: 0.5
};
const FADE = 0.4;

/* İLK YÜKLEME: sahne mount'unu Barba dışına taşı, SplineLoader'ı bir kez kur. */
async function bootSplineOnce() {
  const firstContainer = document.querySelector('[data-barba="container"]');
  const mount = firstContainer && firstContainer.querySelector('.spline-mount');
  if (!mount) { console.warn('[barba-spline] ilk sayfada .spline-mount yok'); return; }

  const host = document.createElement('div');
  host.id = 'spline-persistent';
  document.body.appendChild(host);
  host.appendChild(mount); // DOM'dan koparmadan taşır -> WebGL korunur

  peSpline = new SplineLoader(mount.querySelector('.spline--canvas'), mount);
  window.peSpline = peSpline;
  await peSpline.ready;
}

/* Hedef container'daki spline-mount'tan JSON oku (render YOK), sonra o mount'u kaldır. */
async function readTargetData(container) {
  const mount = container.querySelector('.spline-mount');
  if (!mount) return { animations: [], objectPreferences: [] };
  const data = await peSpline.resolvePageData(mount);
  mount.remove(); // boş ikinci canvas görünmesin
  return data;
}

/* 3) Barba kurulumu */
async function initBarba() {
  await bootSplineOnce();

  barba.init({
    // Yeni gelen container'daki spline-mount'u DOM'a girer girmez gizle/temizle ki
    // boş ikinci bir canvas görünmesin (asıl sahne kalıcı host'ta).
    transitions: [{
      name: 'spline-fade',

      before(trigger) {

        if (trigger && trigger.trigger && trigger.trigger !== 'back' && parents(trigger
            .trigger, '[data-menu="open"]').length) {
          const toggle = parents(trigger.trigger, '[data-menu="open"]')[0].querySelector(
            '.site-nav-toggle');
          toggle.click();
        }

      },
      beforeEnter({ next }) { gsap.set(next.container, { opacity: 0 }); },

      // ESKİ sayfadan çıkış: içerik fadeout + sahne DEFAULT'a (ileri tur + state base'e)
      async leave({ current }) {
        peSpline.killPage();
        await Promise.all([
          fadeOut(current.container, FADE),
          peSpline.animateToDefaults(RESET), // spin + stagger + state animasyonu
        ]);
      },

      // YENİ sayfaya giriş: hedef başlangıç pozuna (ters tur) + animasyonları kur + fadein
      async enter({ next }) {
        window.scrollTo(0, 0);
        const { animations, objectPreferences } = await readTargetData(next.container);

        peSpline.setData(animations, objectPreferences);
        await peSpline.animateToInitial(FORM); // ters spin + stagger
        peSpline.initPage(); // scroll/normal anim + ScrollTrigger.refresh

        await fadeIn(next.container, FADE);
      },
    }],
  });
}

document.addEventListener('DOMContentLoaded', initBarba);

/* Initialize Number Loader in 3 Steps */

initLoaderThreeSteps();

function initOnceFunctions() {
  initLenis();
  siteHeader();

  // refreshInit → lenis.resize BİR KEZ bağlanır. (Önceden init() içindeydi; init() her Barba
  // geçişinde çalıştığı için her seferinde bir listener daha ekleniyordu = leak → her refresh'te
  // lenis.resize N kez çağrılıyor, sayfa gezindikçe kasma artıyordu.)
  ScrollTrigger.addEventListener('refreshInit', () => lenis.resize());
}

barba.hooks.beforeLeave(() => {
  // Spline'ın kendi trigger'ları peSpline.killPage()'de ayrıca temizleniyor;
  // burada site'ın TÜM trigger'larını öldür. enter'da init() yeniden kuruyor.
  // ScrollTrigger.getAll().forEach(st => st.kill());
});

barba.hooks.enter((data) => {
  init();

});

barba.hooks.after((data) => {
  initAnimations();
  ScrollTrigger.refresh(true);
  resetPage();
});

function init() {
  servicesCard();
  serviceLayers();

  initPortfolioFilter();

  contactMap();
  DNAScene();
  aboutClientsScene();

  aboutTeamScene();
  clientsCarousel();

  servicesSection();
  initImagesOnPathScroll();

  parallaxUtils();

  // Görseller yüklendikçe layout değişir → ScrollTrigger pozisyonlarını yenile. Ama HER görselde
  // ayrı refresh yerine TEK debounce'lu refresh (önceden her img load'da refresh çağrılıyordu;
  // mobilde bu refresh spam'i scroll sırasında native momentum'u tıkıyordu). {once} ile listener
  // kendini temizler.
  let _imgRefreshT;
  document.querySelectorAll('img').forEach((img) => {
    if (!img.complete) img.addEventListener('load', () => {
      clearTimeout(_imgRefreshT);
      _imgRefreshT = setTimeout(() => ScrollTrigger.refresh(), 200);
    }, { once: true });
  });

}

function initAnimations() {
  textUtils();
  animUtils();
  gsap.fromTo('.page-wrapper', {
    opacity: 0
  }, {
    opacity: 1
  })

}

document.addEventListener("DOMContentLoaded", () => {
  initOnceFunctions()
  init();

  if (!document.querySelector('.loading-container')) initAnimations();

});
